version: "3"
services:
  app:
    container_name: fastify-example
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm run dev"
  